<?php

namespace App\Helpers;

return [
    ['name' => 'Blue Dress For Women', 'image' => 'img/seed/products/product_img1.jpg',],
    ['name' => 'Leather Gray Tuxedo', 'image' => 'img/seed/products/product_img2.jpg',],
    ['name' => 'Full Sliver Dress', 'image' => 'img/seed/products/product_img3.jpg',],
    ['name' => 'Light Blue Shirt', 'image' => 'img/seed/products/product_img4.jpg',],
    ['name' => 'Blue Jins Shirt', 'image' => 'img/seed/products/product_img8.jpg',],
    ['name' => 'White Black Line Dress', 'image' => 'img/seed/products/product_img7.jpg',],
    ['name' => 'Blue Casual Check Shirt', 'image' => 'img/seed/products/product_img6.jpg',],
    ['name' => 'Blue Dress', 'image' => 'img/seed/products/product_img5.jpg',],
    ['name' => 'Blazers', 'image' => 'img/seed/products/product_img9.jpg',],
    ['name' => '8.5 VA First Charger', 'image' => 'img/seed/products/product_img10.jpg',],
    ['name' => '3.5 VA Charger', 'image' => 'img/seed/products/product_img11.jpg',],
    ['name' => 'MSI Gaming Chair', 'image' => 'img/seed/products/product_img12.jpg',],
    ['name' => 'Fippo shoes', 'image' => 'img/seed/products/product_img13.jpg',],
    ['name' => 'Fippo shoes boys', 'image' => 'img/seed/products/product_img14.jpg',],
    ['name' => 'chanel watch', 'image' => 'img/seed/products/product_img15.jpg',],
    ['name' => 'Ipad Pro', 'image' => 'img/seed/products/product_img16.jpg',],
    ['name' => 'Ipro Tablet', 'image' => 'img/seed/products/product_img17.jpg',],
    ['name' => 'Red Bag', 'image' => 'img/seed/products/product_img18.jpg',],
    ['name' => 'Camon Camera', 'image' => 'img/seed/products/product_img19.jpg',],
    ['name' => 'Sina Sunglasses', 'image' => 'img/seed/products/product_img20.jpg',],
    ['name' => '21 inches Bicycle', 'image' => 'img/seed/products/product_img21.jpg',],
    ['name' => 'Red Headphones', 'image' => 'img/seed/products/product_img22.jpg',],
    ['name' => 'Kids Dress', 'image' => 'img/seed/products/product_img23.jpg',],
    ['name' => 'Myriad Chairs', 'image' => 'img/seed/products/product_img24.jpg',],
    ['name' => 'Iphone 8 with Ipod', 'image' => 'img/seed/products/product_img25.jpg',],
    ['name' => 'Blue Bag', 'image' => 'img/seed/products/product_img26.jpg',],
    ['name' => 'Ios Laptop', 'image' => 'img/seed/products/product_img27.jpg',],
    ['name' => 'Red Dress', 'image' => 'img/seed/products/product_img28.jpg',],
    ['name' => 'Iwatch Pro', 'image' => 'img/seed/products/product_img29.jpg',],
    ['name' => 'Ios Monitor', 'image' => 'img/seed/products/product_img30.jpg',],
    ['name' => 'Ios Monitor Slim', 'image' => 'img/seed/products/product_img31.jpg',],
    ['name' => 'Boom Box', 'image' => 'img/seed/products/product_img32.jpg',],
    ['name' => 'Dell Laptop', 'image' => 'img/seed/products/product_img33.jpg',],
    ['name' => 'G-shock Watch', 'image' => 'img/seed/products/product_img34.jpg',],
    ['name' => 'Big Box Headphones', 'image' => 'img/seed/products/product_img35.jpg',],
    ['name' => 'Android Mobile', 'image' => 'img/seed/products/product_img36.jpg',],
    ['name' => 'Music box', 'image' => 'img/seed/products/product_img37.jpg',],
    ['name' => 'Apple Gaming Chair', 'image' => 'img/seed/products/product_img38.jpg',],
    ['name' => 'Silver Watch', 'image' => 'img/seed/products/product_img39.jpg',],
    ['name' => 'Samsung Galaxy X', 'image' => 'img/seed/products/product_img40.jpg',],
    ['name' => 'Msi Laptop', 'image' => 'img/seed/products/product_img41.jpg',],
    ['name' => 'Forehead Thermometer', 'image' => 'img/seed/products/product_img42.jpg',],
    ['name' => 'Iwatch 15', 'image' => 'img/seed/products/product_img43.jpg',],
    ['name' => 'X-box controller', 'image' => 'img/seed/products/product_img44.jpg',],
    ['name' => 'Nike Shoe', 'image' => 'img/seed/products/product_img45.jpg',],
];
